### ISSUE TITLE
Error while creating a payment

### ISSUE THREAD

**Issue by kramer65** [mollie/mollie-api-python#3]
I'm trying to do some test payments which have been going fairly well, but I now ran into a weird problem. I'm trying to create a payment like this:

    payment = mollie.payments.create({
        'amount': str(bill.total_amount),
        'description': bill.description,
        'redirectUrl': url_for('myBills', _external=True) + '#' + str(bill.id),
        'metadata': {'order_nr': bill.id},
        'method': 'ideal',
        'issuer': "ideal_TESTNL99"
    })

This used to work fine, but I now suddenly get the error below. Does anybody know what's wrong here?
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/kramer65/opo/app/views/webviews.py", line 462, in myBills
    'issuer': "ideal_TESTNL99"
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 54, in create
    return self.rest_create(data)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 27, in rest_create
    result = self.performApiCall(self.REST_CREATE, path, data, params)
  File "/usr/local/lib/python2.7/dist-packages/Mollie/API/Resource/Base.py", line 85, in performApiCall
    raise error
Error
```

**Comment by willemstuursma** [comment]
We've had a minor network issue, could you just try again?

**Comment by kramer65** [comment]
I still get the same error..

**Comment by kramer65** [comment]
Misschien is het ook goed om een wat meer specifieke error te geven. Iets als een MollieConnectionError oid?

**Comment by mollierobbert** [comment]
Hi Hielke, the `Error` does contain a message pointing you to the cause of the issue, as you can see in the `performApiCall` method:

https://github.com/mollie/mollie-api-python/blob/master/Mollie/API/Resource/Base.py#L75

Please try catching the error when creating a payment to see what's up:

    try:
        payment = mollie.payments.create(/* Your arguments */)
    except Error as e:
        print "Mollie API error message: " + e.message

Please let us know if this helps you find the problem.

**Comment by kramer65** [comment]
Ah, that helped. Turned out the error was because "The amount is higher than the maximum.".

Everything works as expected again.

**Comment by mollierobbert** [comment]
Glad to hear this solved your issue. For an overview of the minimum and maximum amounts of each of your payment methods, use the `methods` resource:

    methods = mollie.methods.all()

    for method in methods:
        print "Method: " + method['description']
        print "Minimum amount: " + method['amount']['minimum']
        print "Maximum amount: " + method['amount']['maximum']

For more information, [see the Methods section of our API docs](https://www.mollie.com/en/docs/methods).
